In [1]:
x = {}
x = dict()

In [2]:
type(x)

dict

In [4]:
dict1 =  {1:"a", "a":3, "g":"true", True: False, 4.6: " "}

dict1

{1: False, 'a': 3, 'g': 'true', 4.6: ' '}

In [11]:
dict1[1]

False

In [13]:
dict1.values()

dict_values([False, 3, 'true', ' '])

In [15]:
dict1

{1: False, 'a': 3, 'g': 'true', 4.6: ' '}

In [14]:
dict1.items()

dict_items([(1, False), ('a', 3), ('g', 'true'), (4.6, ' ')])

In [16]:
dict1.keys()

dict_keys([1, 'a', 'g', 4.6])

In [17]:
dict1.get('g')

'true'

In [18]:
dict1.get(a)

NameError: name 'a' is not defined

In [19]:
dict1[1] = "Hello"
dict1

{1: 'Hello', 'a': 3, 'g': 'true', 4.6: ' '}

In [20]:
dict1.update({"g": "BMW"})
dict1

{1: 'Hello', 'a': 3, 'g': 'BMW', 4.6: ' '}

In [21]:
del dict1["hello"]

KeyError: 'hello'

In [22]:
del dict1

In [23]:
dict1

NameError: name 'dict1' is not defined

In [24]:
z = (9,9,0)

In [25]:
z[2]

0

In [29]:
cars = {
    "toyota": "Revo",
    "Kia": "Rio",
    "Honda": "CRH"
       }

In [30]:
for i in cars:
    print(i)

toyota
Kia
Honda


In [32]:
for i,j in cars.items():
    print(i,j)

toyota Revo
Kia Rio
Honda CRH


In [33]:
for i in cars.values():
    print(i)

Revo
Rio
CRH


In [35]:
lst = []

for i in cars.keys():
    lst.append(i)

lst

['toyota', 'Kia', 'Honda']

In [36]:
motorcycle = {
    "honda" : ["70", 125, "CBR"],
    "Yamha": ["MT-03", "R3", "R1M"]
}

In [37]:
motorcycle

{'honda': ['70', 125, 'CBR'], 'Yamha': ['MT-03', 'R3', 'R1M']}

In [40]:
motorcycle["honda"][2]

'CBR'

In [41]:
motorcycle["honda"][1]

125

In [42]:
import pandas as pd
import numpy as np

In [43]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [44]:
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [50]:
frame["year","state", "pop"]]

InvalidIndexError: ([0], ['year', 'state', 'pop'])

In [54]:
nest_dict = {
    "Toyota":{
        "CBR": 300,
        "SHadow": 1200
    },
    "Kawasaki":{
        'Nija': {
            "hyper": "H2R",
            "SSuper" : "ZX10R"
        }
    }
}

In [55]:
nest_dict

{'Toyota': {'CBR': 300, 'SHadow': 1200},
 'Kawasaki': {'Nija': {'hyper': 'H2R', 'SSuper': 'ZX10R'}}}

In [58]:
for i in nest_dict.items():
    print(i)

('Toyota', {'CBR': 300, 'SHadow': 1200})
('Kawasaki', {'Nija': {'hyper': 'H2R', 'SSuper': 'ZX10R'}})


In [59]:
nest_dict["Toyota"]

{'CBR': 300, 'SHadow': 1200}

In [60]:
nest_dict["Toyota"]["SHadow"]

1200

In [61]:
nest_dict["Toyota"][1]

KeyError: 1

In [62]:
hash("string")

6070483483404634666

In [63]:
hash(2)

2

In [64]:
hash(3.6)

1383505805528216579

In [65]:
hash(True)

1

In [66]:
hash((3,4,5))

4003026094496801395

In [67]:
hash((3,4,[5,6,7]))

TypeError: unhashable type: 'list'

In [68]:
hash([1,2,3,4])

TypeError: unhashable type: 'list'

In [69]:
hash({"X": 2, 'y':5})

TypeError: unhashable type: 'dict'

In [70]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr1 = arr[3:7]

arr1

array([3, 4, 5, 6])

In [72]:
arr1[:] = 87

In [73]:
arr1

array([87, 87, 87, 87])

In [74]:
arr

array([ 0,  1,  2, 87, 87, 87, 87,  7,  8,  9])

In [75]:
arr3 = arr[3:7].copy()

In [76]:
arr3

array([87, 87, 87, 87])

In [77]:
arr3 [:] = 0

In [78]:
arr3

array([0, 0, 0, 0])

In [79]:
arr

array([ 0,  1,  2, 87, 87, 87, 87,  7,  8,  9])

In [82]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
mat.dtype

dtype('int32')

In [87]:
mat.shape

(3, 3)

In [88]:
mat.astype("float")

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [89]:
mat.dtype

dtype('int32')

In [83]:
import numpy as np

my_arr = np.arange(1_000_000)

my_list = list(range(1_000_000))

In [84]:
%timeit my_arr * 2

1.95 ms ± 51.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [85]:
%timeit [x * 2 for x in my_list]

95.5 ms ± 3.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
