In [1]:
import numpy as np

In [2]:
arr = np.array([2,9,16,25])
arr

array([ 2,  9, 16, 25])

In [3]:
np.sqrt(arr)

array([1.41421356, 3.        , 4.        , 5.        ])

In [4]:
np.square(arr)

array([  4,  81, 256, 625])

In [5]:
np.exp(arr)

array([7.38905610e+00, 8.10308393e+03, 8.88611052e+06, 7.20048993e+10])

In [6]:
W = np.array([1.0,2.5,-3.3])
X = np.array([10,20,30])
b = 4

In [7]:
f_wb = np.dot(W,X) + b
f_wb

-35.0