In [1]:
import numpy as np

In [5]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [6]:
%timeit my_arr2 = my_arr * 2

2.47 ms ± 80 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
%timeit my_list2 = [x * 2 for x in my_list]

137 ms ± 24.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
137/2.47

55.46558704453441

In [9]:
dat = np.array([[1.5,-0.1,3], [0,-3,6.5]])

In [10]:
dat

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [11]:
dat * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [12]:
dat +dat 

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [13]:
dat.shape

(2, 3)

In [17]:
x1 = [6,7.5,8,0,2]
x1

[6, 7.5, 8, 0, 2]

In [16]:
arr1 = np.array(x1)
arr1

array([6. , 7.5, 8. , 0. , 2. ])

In [18]:
x2 = [[6,7.5,8,0,2],[6,7.5,8,0,2]]

arr2 = np.array(x2)
arr2

array([[6. , 7.5, 8. , 0. , 2. ],
       [6. , 7.5, 8. , 0. , 2. ]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 5)

In [22]:
arr1.dtype

dtype('float64')

In [24]:
arr2.dtype

dtype('float64')

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
np.empty((2,3,2))

array([[[1.08571074e-311, 2.42092166e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.18831764e-312, 6.82116729e-043]],

       [[6.20156487e-091, 7.96522783e-042],
        [1.52495952e-052, 5.04456577e+174],
        [6.99196247e+228, 1.10678370e-046]]])

In [28]:
np.empty((2,3,2))[0]

array([[1.08571074e-311, 2.42092166e-322],
       [0.00000000e+000, 0.00000000e+000],
       [1.18831764e-312, 6.82116729e-043]])

In [30]:
np.ones_like(np.empty((2,3,2)))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [31]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [32]:
arr2 = np.array([1.2,2.4,3.5], dtype=np.int32)
arr2

array([1, 2, 3])

In [33]:
arr2.dtype

dtype('int32')

In [34]:
arr2.astype(np.float64)

array([1., 2., 3.])

In [35]:
arr2.astype(np.string_)

array([b'1', b'2', b'3'], dtype='|S11')

In [36]:
arr2

array([1, 2, 3])

In [37]:
arr2 * arr2


array([1, 4, 9])

In [38]:
arr2**2 

array([1, 4, 9])

In [39]:
1/arr2

array([1.        , 0.5       , 0.33333333])

In [40]:
arr2**2  < arr2

array([False, False, False])

In [41]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[7]

7

In [43]:
arr[5:8]

array([5, 6, 7])

In [44]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])